server:
  port: 8090
  tomcat:
    uri-encoding: UTF-8
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  devtools:
    remote:
      secret: wxd
  datasource:
    name: order-mybatis
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://127.0.1:3306/order_test
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 1000
      max-request-size: 1000
logging:
  path: ./logs
  level:
    root: INFO
custom:
  name: wangXiaodan
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.erui.order.model.entity
pagehelper:
  reasonable: true
  support-methods-arguments: true
  helper-dialect: mysql

